# Place your local configuration in /etc/mosquitto/conf.d/

# Global Settings
# pid_file /run/mosquitto/mosquitto.pid
persistence true
persistence_location /var/lib/mosquitto/
log_dest file /var/log/mosquitto/mosquitto.log

# Global Security Settings
allow_anonymous true

# Standard MQTT Listener
listener 1883

# WebSockets Listener
listener 9001
protocol websockets

# Include additional configs
include_dir /etc/mosquitto/conf.d
